### ISSUE TITLE
Support for Android API levels <26

### ISSUE THREAD

**Issue by mikovali** [open-eid/cdoc4j#2]
`java.nio.file` package is supported on API levels 26+.
https://developer.android.com/reference/java/nio/file/package-summary

https://github.com/open-eid/cdoc4j/blob/master/src/main/java/org/openeid/cdoc4j/CDOCBuilder.java#L99
Should implement this method without using classes in `java.nio.file` package.

**Comment by andresvoll** [comment]
As a workaround could you construct the `DataFile` instance yourself and use the `CDOCBuilder#withDataFile(DataFile)` method instead?

**Comment by andresvoll** [comment]
Since the release of [version 1.2](https://mvnrepository.com/artifact/org.open-eid.cdoc4j/cdoc4j/1.2) the API and its core performance has been  reworked, so this issue should be obsolete.
