### ISSUE TITLE
Create possibility to decrypt container in memory and introduce MIME type value in the DataFile object

### ISSUE THREAD

**Issue by stanislav-degtjarjov** [open-eid/cdoc4j#5]
* Create possibility to decrypt container in memory
Example of the decrypt return type:
ListOf(
DataFile{
String name, 
long size,
String mimeType, // NB! Should be introduced. Mime type of the file was added to the container
Date creationDate, // creation date of the file was added to the container (if possible) 
byte[] body; // 
});

Proposal: We can create 2 types of DataFile objects, one is read once, and another is read multiple times.

**Comment by naare** [comment]
This is introduced in v1.3
